/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

import business.LibrarySystem;
import javax.swing.*;
/**
 *
 * @author xuanliliu
 */
public class AdminWorkAreaPanel extends javax.swing.JPanel {
private final business.LibrarySystem system;
private final business.directory.BranchDirectory bd;
    /**
     * Creates new form AdminWorkAreaPanel
     */
    public AdminWorkAreaPanel(LibrarySystem system){
        this.system = system;
        this.bd = system.getBranchDirectory();
        initComponents();
        initTableModel();
        bindEvents();
        loadTable();
    }
    private void initTableModel() {
    javax.swing.table.DefaultTableModel m = new javax.swing.table.DefaultTableModel(
            // 多两列：Building（Library 的 buildingNo）和 Manager
            new Object[]{"ID","Name","Building","Manager"}, 0) {
        @Override public boolean isCellEditable(int r,int c){ return false; }
        @Override public Class<?> getColumnClass(int columnIndex) {
            // ID 用 Integer，其它都 String
            return columnIndex==0 ? Integer.class : String.class;
        }
    };
    tblBranches.setModel(m);
    tblBranches.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
}
    private void bindEvents() {
    btnAddBranch.addActionListener(e -> onAdd());
    btnDeleteBranch.addActionListener(e -> onDelete());
    btnRefresh.addActionListener(e -> loadTable());
    tfBranchName.addActionListener(e -> onAdd()); // 回车即可新增
}
    private void loadTable() {
    javax.swing.table.DefaultTableModel m =
            (javax.swing.table.DefaultTableModel) tblBranches.getModel();
    m.setRowCount(0);
    for (business.model.Branch b : bd.getAll()) {
        // 取 Library 的 buildingNo，当作 Building 列
        String building = "";
        if (b.getLibrary() != null) {
            building = b.getLibrary().getBuildingNo();
        }

        // 取 Manager 名字
        String manager = "";
        if (b.getManager() != null) {
            manager = b.getManager().getName() + " (Emp#" + b.getManager().getEmployeeId() + ")";
        }

        m.addRow(new Object[]{
                b.getId(),
                b.getName(),
                building,
                manager
        });
    }
}
    private void onAdd() {
    String name = tfBranchName.getText().trim();
    String buildingNo = tfBuildingNo.getText().trim();

    if (name.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please input branch name.");
        return;
    }
    if (buildingNo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please input building number.");
        return;
    }

    // 1) 创建 Library
    business.model.Library lib =
            system.getLibraryDirectory().create(buildingNo);

    // 2) 创建 Branch 并关联 Library
    business.model.Branch b = bd.create(name);
    b.setLibrary(lib);

    // 清空输入框
    tfBranchName.setText("");
    tfBuildingNo.setText("");

    loadTable();
}

    private void onDelete() {
    int row = tblBranches.getSelectedRow();
    if (row < 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a row to delete.");
        return;
    }
    int id = (Integer) tblBranches.getValueAt(row, 0);
    int ok = javax.swing.JOptionPane.showConfirmDialog(
            this, "Delete branch ID " + id + " ?", "Confirm",
            javax.swing.JOptionPane.OK_CANCEL_OPTION);
    if (ok != javax.swing.JOptionPane.OK_OPTION) return;

    boolean success = bd.deleteById(id); // 你的 BranchDirectory 需要有这个方法
    if (!success) {
        javax.swing.JOptionPane.showMessageDialog(this, "Delete failed.");
    }
    loadTable();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBranches = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfBranchName = new javax.swing.JTextField();
        btnAddBranch = new javax.swing.JButton();
        btnDeleteBranch = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        tfBuildingNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Admin Branch Management");

        tblBranches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBranches);

        jLabel2.setText("Branch Name");

        btnAddBranch.setText("Add");

        btnDeleteBranch.setText("Delete");

        btnRefresh.setText("Refresh");

        tfBuildingNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuildingNoActionPerformed(evt);
            }
        });

        jLabel3.setText("Building No");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddBranch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteBranch))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfBuildingNo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfBranchName, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnRefresh)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfBranchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBuildingNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddBranch)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDeleteBranch)
                        .addGap(10, 10, 10)))
                .addComponent(btnRefresh)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfBuildingNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuildingNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuildingNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBranch;
    private javax.swing.JButton btnDeleteBranch;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBranches;
    private javax.swing.JTextField tfBranchName;
    private javax.swing.JTextField tfBuildingNo;
    // End of variables declaration//GEN-END:variables
}
