/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

/**
 *
 * @author xuanliliu
 */
public class AdminManagerPanel extends javax.swing.JPanel {

    private final business.LibrarySystem system;
    /**
     * Creates new form AdminManagerPanel
     */
    public AdminManagerPanel() {
        this.system = null;
        initComponents();
    }
    public AdminManagerPanel(business.LibrarySystem system) {
    this.system = system;
    if (system.getLibraryDirectory().getAll().isEmpty()) {
        business.model.Library l1 = system.getLibraryDirectory().create("B1-101");
        business.model.Branch  b1 = system.getBranchDirectory().create("Downtown");
        b1.setLibrary(l1);
    }
    initComponents();
    initUIData();
    bindEvents();
}
    
    
    private void initUIData() {
    // 载入 Library 下拉
    javax.swing.DefaultComboBoxModel<business.model.Library> modelLib = new javax.swing.DefaultComboBoxModel<>();
    for (business.model.Library lib : system.getLibraryDirectory().getAll()){
        modelLib.addElement(lib);
    }
    cbLibrary.setModel(modelLib);
    // 显示 buildingNo
    cbLibrary.setRenderer((list, value, index, isSelected, cellHasFocus) ->
            new javax.swing.JLabel(value==null? "" : value.getBuildingNo()));

    // 载入员工下拉
    reloadEmployees();

    // 触发一次，显示当前经理
    if (modelLib.getSize() > 0) {
        cbLibrary.setSelectedIndex(0);
        updateCurrentManager();
    }
}
    private void reloadEmployees(){
    javax.swing.DefaultComboBoxModel<business.model.people.Employee> modelEmp =
            new javax.swing.DefaultComboBoxModel<>();
    for (business.model.people.Employee e : system.getEmployeeDirectory().getAll()){
        modelEmp.addElement(e);
    }
    cbEmployee.setModel(modelEmp);
    // 显示名字+工号
    cbEmployee.setRenderer((list, value, index, isSelected, cellHasFocus) ->
            new javax.swing.JLabel(value==null? "" : value.getName() + " (#" + value.getEmployeeId() + ")"));
}
    private void updateCurrentManager(){
    business.model.Library lib = (business.model.Library) cbLibrary.getSelectedItem();
    if (lib == null) { lblCurrentManager.setText("-"); return; }
    business.model.people.Employee m = lib.getManager();
    lblCurrentManager.setText(m==null ? "(none)" : m.getName() + " (#" + m.getEmployeeId() + ")");
}

    private void bindEvents(){
    cbLibrary.addActionListener(e -> updateCurrentManager());

    btnAssign.addActionListener(e -> {
        business.model.Library lib = (business.model.Library) cbLibrary.getSelectedItem();
        business.model.people.Employee emp = (business.model.people.Employee) cbEmployee.getSelectedItem();
        if (lib==null || emp==null){
            javax.swing.JOptionPane.showMessageDialog(this,"Pick a library and an employee.");
            return;
        }
        // 同步设置到 Library 和 Branch（如果你的 Branch 也需要反映，可以按需设置）
        lib.setManager(emp);
        // 若需要：找到有这个 library 的 branch 并设置 manager（可选）
        for (business.model.Branch b : system.getBranchDirectory().getAll()){
            if (b.getLibrary() == lib){ b.setManager(emp); }
        }
        updateCurrentManager();
        javax.swing.JOptionPane.showMessageDialog(this,"Assigned.");
    });

    btnCreateEmp.addActionListener(e -> {
        String name = tfEmpName.getText().trim();
        int exp;
        try { exp = Integer.parseInt(tfEmpExp.getText().trim()); }
        catch (Exception ex){
            javax.swing.JOptionPane.showMessageDialog(this,"Experience must be an integer.");
            return;
        }
        if (name.isEmpty()){ javax.swing.JOptionPane.showMessageDialog(this,"Name required."); return; }

        // 创建并加入目录
        business.model.people.Employee emp = system.getEmployeeDirectory().create(name, exp);
        reloadEmployees(); // 让下拉刷新到新员工
        cbEmployee.setSelectedItem(emp);

        // 直接指派给当前库
        business.model.Library lib = (business.model.Library) cbLibrary.getSelectedItem();
        if (lib != null){
            lib.setManager(emp);
            for (business.model.Branch b : system.getBranchDirectory().getAll()){
                if (b.getLibrary() == lib){ b.setManager(emp); }
            }
        }
        tfEmpName.setText(""); tfEmpExp.setText("");
        updateCurrentManager();
        javax.swing.JOptionPane.showMessageDialog(this,"Created and assigned.");
    });
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbLibrary = new javax.swing.JComboBox<business.model.Library>()
        ;
        jLabel2 = new javax.swing.JLabel();
        lblCurrentManager = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbEmployee = new javax.swing.JComboBox<business.model.people.Employee>()
        ;
        btnAssign = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfEmpName = new javax.swing.JTextField();
        tfEmpExp = new javax.swing.JTextField();
        btnCreateEmp = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel1.setText("Library");

        jLabel2.setText("Current Manager");

        lblCurrentManager.setText("-");

        jLabel4.setText("Assign Existing Employee");

        jLabel5.setText("Employee:");

        btnAssign.setText("Assign");

        jLabel6.setText("Create New Employee");

        jLabel7.setText("Name:");

        jLabel8.setText("Experience:");

        btnCreateEmp.setText("Create");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCurrentManager)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAssign))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cbLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfEmpExp, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(58, 58, 58)
                                        .addComponent(tfEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(btnCreateEmp)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblCurrentManager)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAssign))))
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfEmpExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnCreateEmp)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnCreateEmp;
    private javax.swing.JComboBox<business.model.people.Employee> cbEmployee;
    private javax.swing.JComboBox<business.model.Library> cbLibrary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCurrentManager;
    private javax.swing.JTextField tfEmpExp;
    private javax.swing.JTextField tfEmpName;
    // End of variables declaration//GEN-END:variables
}
