/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

/**
 *
 * @author xuanliliu
 */
public class AdminMainPanel extends javax.swing.JPanel {
    private final business.LibrarySystem system;
    private javax.swing.JTabbedPane tabs;

    /**
     * Creates new form AdminMainPanel
     */
    public AdminMainPanel() {
        this.system = null;
        initComponents();
    }
    public AdminMainPanel(business.LibrarySystem system) {
        this.system = system;
        initComponents();
        // 加两个页签
        jTabbedPane1.addTab("Branches", new ui.admin.AdminWorkAreaPanel(system));
        jTabbedPane1.addTab("Managers", new ui.admin.AdminManagerPanel(system));
        jTabbedPane1.addTab("Employees", new ui.admin.AdminEmployeePanel(system));
        
        jTabbedPane1.addTab("Customers", new ui.admin.AdminCustomerPanel(system));
        jTabbedPane1.addTab("Users",     new ui.admin.AdminUserPanel(system));
        
        jButton1.setText("Logout");

        // 先从原有位置移除
        this.remove(jButton1);
        
        javax.swing.JPanel south = new javax.swing.JPanel();
        south.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));
        south.add(jButton1);
        
        this.add(south, java.awt.BorderLayout.SOUTH);

        // 强制刷新
        this.revalidate();
        this.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());
        add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);

    if (win != null) {
        // 先隐藏，再释放资源，确保窗体真的关掉
        win.setVisible(false);
        win.dispose();
    }

    // 2. 回到登录界面
    new ui.LoginFrame().setVisible(true); 
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
